const Complaints = [
    {
      studentName: "John Doe",
      rollNumber: "12345",
      roomNumber: "A-101",
      category: "Electrical",
      status: "Waiting for Approval",
      complaint: "Electrical issues in the room.",
    },
    {
      studentName: "John Doe",
      rollNumber: "12345",
      roomNumber: "A-101",
      category: "Electrical",
      status: "Pending",
      complaint: "Electrical issues in the room.",
    },{
      studentName: "John Doe",
      rollNumber: "12345",
      roomNumber: "A-101",
      category: "Electrical",
      status: "Done",
      complaint: "Electrical issues in the room.",
    },{
      studentName: "John Doe",
      rollNumber: "12345",
      roomNumber: "A-101",
      category: "Electrical",
      status: "Pending",
      complaint: "Electrical issues in the room.",
    },{
      studentName: "John Doe",
      rollNumber: "12345",
      roomNumber: "A-101",
      category: "Electrical",
      status: "Pending",
      complaint: "Electrical issues in the room.",
    },{
      studentName: "John Doe",
      rollNumber: "12345",
      roomNumber: "A-101",
      category: "Electrical",
      status: "Pending",
      complaint: "Electrical issues in the room.",
    },{
      studentName: "John Doe",
      rollNumber: "12345",
      roomNumber: "A-101",
      category: "Electrical",
      status: "Pending",
      complaint: "Electrical issues in the room.",
    },{
      studentName: "John Doe",
      rollNumber: "12345",
      roomNumber: "A-101",
      category: "Electrical",
      status: "Pending",
      complaint: "Electrical issues in the room.",
    },{
      studentName: "John Doe",
      rollNumber: "12345",
      roomNumber: "A-101",
      category: "Electrical",
      status: "Pending",
      complaint: "Electrical issues in the room.",
    },{
      studentName: "John Doe",
      rollNumber: "12345",
      roomNumber: "A-101",
      category: "Electrical",
      status: "Pending",
      complaint: "Electrical issues in the room.",
    },{
      studentName: "John Doe",
      rollNumber: "12345",
      roomNumber: "A-101",
      category: "Electrical",
      status: "Pending",
      complaint: "Electrical issues in the room.",
    },{
      studentName: "John Doe",
      rollNumber: "12345",
      roomNumber: "A-101",
      category: "Electrical",
      status: "Pending",
      complaint: "Electrical issues in the room.",
    },{
      studentName: "John Doe",
      rollNumber: "12345",
      roomNumber: "A-101",
      category: "Electrical",
      status: "Pending",
      complaint: "Electrical issues in the room.",
    },{
      studentName: "John Doe",
      rollNumber: "12345",
      roomNumber: "A-101",
      category: "Electrical",
      status: "Pending",
      complaint: "Electrical issues in the room.",
    },{
      studentName: "John Doe",
      rollNumber: "12345",
      roomNumber: "A-101",
      category: "Electrical",
      status: "Pending",
      complaint: "Electrical issues in the room.",
    },{
      studentName: "John Doe",
      rollNumber: "12345",
      roomNumber: "A-101",
      category: "Electrical",
      status: "Pending",
      complaint: "Electrical issues in the room.",
    },{
      studentName: "John Doe",
      rollNumber: "12345",
      roomNumber: "A-101",
      category: "Electrical",
      status: "Pending",
      complaint: "Electrical issues in the room.",
    },
  ];

export default Complaints;